# Generated by Django 6.0 on 2026-01-17 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_level', models.PositiveIntegerField(default=10)),
                ('base_exp', models.PositiveIntegerField(default=50)),
                ('exp_growth', models.FloatField(default=1.3)),
                ('effect_name', models.CharField(max_length=100)),
                ('effect_description', models.TextField(blank=True)),
                ('effect_value_per_level', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='buildings/')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='game_buildi_slug_8a8eb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_balance', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль игрока',
            },
        ),
        migrations.CreateModel(
            name='FarmField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Уровень поля (размер = level * 5)')),
                ('max_cells', models.PositiveIntegerField(default=25, help_text='Макс. клеток = level^2 * 25')),
                ('expansion_cost_coins', models.PositiveIntegerField(default=1000, help_text='Стоимость следующего расширения')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_field', to='game.playerprofile')),
            ],
            options={
                'verbose_name': 'Поле фермы',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price_coins', models.PositiveIntegerField(default=0)),
                ('is_seed', models.BooleanField(default=False)),
                ('is_harvest', models.BooleanField(default=False)),
                ('grow_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('harvest_yield', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.itemcategory')),
                ('harvest_item', models.ForeignKey(blank=True, help_text='Если это семя, то сюда ставим связанный урожай', limit_choices_to={'is_harvest': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_item', to='game.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Позиция: row * grid_size + col')),
                ('object_type', models.CharField(choices=[('field', 'Поле'), ('building', 'Здание')], default='field', max_length=20)),
                ('object_data', models.JSONField(blank=True, default=dict)),
                ('is_anchor', models.BooleanField(default=True)),
                ('anchor_position', models.PositiveIntegerField(blank=True, null=True)),
                ('size_w', models.PositiveIntegerField(blank=True, null=True)),
                ('size_h', models.PositiveIntegerField(blank=True, null=True)),
                ('planted_at', models.DateTimeField(blank=True, null=True)),
                ('grow_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'position'], name='game_cell_profile_618f91_idx'), models.Index(fields=['profile', 'anchor_position'], name='game_cell_profile_a57525_idx'), models.Index(fields=['profile', 'is_anchor'], name='game_cell_profile_29dc13_idx')],
                'unique_together': {('profile', 'position')},
            },
        ),
        migrations.CreateModel(
            name='AreaLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_start', models.IntegerField()),
                ('col_start', models.IntegerField()),
                ('rows', models.IntegerField(help_text='Высота зоны в клетках')),
                ('cols', models.IntegerField(help_text='Ширина зоны в клетках')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlock_cost', models.PositiveIntegerField(default=1000)),
                ('building_type', models.CharField(blank=True, max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'is_unlocked'], name='game_arealo_profile_aaa202_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'row_start', 'col_start', 'rows', 'cols'), name='uniq_lock_rect_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.shopitem')),
            ],
            options={
                'indexes': [models.Index(fields=['player'], name='game_invent_player__c0f460_idx'), models.Index(fields=['item'], name='game_invent_item_id_2ead69_idx')],
                'unique_together': {('player', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='game_usersk_user_id_c079af_idx'), models.Index(fields=['skill'], name='game_usersk_skill_i_a16120_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
