# Generated by Django 6.0 on 2026-01-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingtype',
            name='image',
        ),
    ]
