# Generated by Django 6.0 on 2025-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='planted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
