# Generated by Django 6.0 on 2026-01-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_buildingtype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('price_paid', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='game.buildingtype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_placements', to='game.playerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'row', 'col'], name='game_buildi_profile_7ccf1a_idx'), models.Index(fields=['profile', 'building_type'], name='game_buildi_profile_addbb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_row', models.PositiveIntegerField()),
                ('chunk_col', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField(default=10)),
                ('price_paid', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_chunks', to='game.playerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'chunk_row', 'chunk_col'], name='game_fieldc_profile_8301ef_idx'), models.Index(fields=['profile', 'price_paid'], name='game_fieldc_profile_c5bbc5_idx')],
                'unique_together': {('profile', 'chunk_row', 'chunk_col')},
            },
        ),
    ]
