# Generated by Django 6.0 on 2025-12-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_coins', models.PositiveIntegerField(default=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.plant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.seed')),
            ],
            options={
                'unique_together': {('owner', 'seed')},
            },
        ),
    ]
