# Generated by Django 6.0 on 2026-03-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_buildingplacement_fieldchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_row', models.PositiveIntegerField()),
                ('cell_col', models.PositiveIntegerField()),
                ('planted_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('growing', 'Растёт'), ('ready', 'Готов к сбору'), ('harvested', 'Собран')], default='growing', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='game.buildingplacement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_plots', to='game.playerprofile')),
                ('seed', models.ForeignKey(limit_choices_to={'is_seed': True}, on_delete=django.db.models.deletion.CASCADE, to='game.shopitem')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'status'], name='game_farmpl_profile_9c25d3_idx'), models.Index(fields=['building', 'cell_row', 'cell_col'], name='game_farmpl_buildin_2f4e85_idx')],
                'unique_together': {('profile', 'building', 'cell_row', 'cell_col')},
            },
        ),
    ]
