# Generated by Django 6.0 on 2026-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_farm_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='harvest_yield',
            field=models.PositiveIntegerField(default=2, help_text='Количество урожая при сборе'),
        ),
    ]
