# Generated by Django 6.0 on 2025-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_seed_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='harvest_reward',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plant',
            name='seed_price',
            field=models.IntegerField(default=10),
        ),
    ]
