# Generated by Django 6.0 on 2026-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_set_harvest_yield_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='base_exp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='exp_growth',
            field=models.FloatField(default=1.5),
        ),
    ]
