# Generated by Django 6.0 on 2026-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_add_profile_exp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='building_type',
            field=models.CharField(choices=[('field', 'Поле'), ('extraction', 'Добыча ресурсов'), ('processing', 'Переработка'), ('production', 'Производство')], default='field', max_length=20),
        ),
        migrations.AddIndex(
            model_name='buildingtype',
            index=models.Index(fields=['building_type'], name='game_buildi_buildin_cad9b4_idx'),
        ),
    ]
