# Generated by Django 6.0 on 2025-12-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playerseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='sell_price_coins',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.DeleteModel(
            name='PlayerSeed',
        ),
    ]
