# Generated by Django 6.0 on 2026-03-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_add_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('recipe_group', models.CharField(choices=[('field', 'Поле'), ('extraction', 'Добыча ресурсов'), ('processing', 'Переработка'), ('production', 'Производство')], default='production', max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('output_quantity', models.PositiveIntegerField(default=1)),
                ('output_item', models.ForeignKey(help_text='Готовый продукт', on_delete=django.db.models.deletion.CASCADE, related_name='recipes_as_output', to='game.shopitem')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.shopitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='game.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('ready', 'Готов'), ('completed', 'Завершён')], default='running', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_processes', to='game.buildingplacement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_processes', to='game.playerprofile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.recipe')),
            ],
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['recipe_group'], name='game_recipe_recipe__af1df3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='game_recipe_slug_4a5923_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'item')},
        ),
        migrations.AddIndex(
            model_name='recipeprocess',
            index=models.Index(fields=['profile', 'status'], name='game_recipe_profile_8a850d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeprocess',
            index=models.Index(fields=['building', 'status'], name='game_recipe_buildin_ed9564_idx'),
        ),
    ]
