# Generated by Django 6.0 on 2026-03-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_add_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_group',
            field=models.CharField(choices=[('field', 'Поле'), ('processing', 'Переработка'), ('production', 'Производство')], default='production', max_length=20),
        ),
        migrations.CreateModel(
            name='ExtractionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('output_quantity', models.PositiveIntegerField(default=1)),
                ('building_type', models.ForeignKey(limit_choices_to={'building_type': 'extraction'}, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_resources', to='game.buildingtype')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_sources', to='game.shopitem')),
            ],
            options={
                'verbose_name': 'Ресурс добычи',
                'verbose_name_plural': 'Ресурсы добычи',
            },
        ),
        migrations.CreateModel(
            name='ExtractionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('next_harvest_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Работает'), ('paused', 'Приостановлен')], default='running', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_processes', to='game.buildingplacement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_processes', to='game.playerprofile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.extractionresource')),
            ],
        ),
        migrations.AddIndex(
            model_name='extractionresource',
            index=models.Index(fields=['building_type'], name='game_extrac_buildin_06899c_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionprocess',
            index=models.Index(fields=['profile', 'status'], name='game_extrac_profile_8c8ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionprocess',
            index=models.Index(fields=['building', 'status'], name='game_extrac_buildin_dc95c9_idx'),
        ),
    ]
