# Generated by Django 6.0 on 2025-12-23 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_plant_harvest_yield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('seed', 'Seed'), ('product', 'Product')], default='seed', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('owner', 'seed', 'item_type')},
        ),
    ]
