# Generated by Django 6.0 on 2025-12-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_inventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='sell_price_coins',
        ),
        migrations.CreateModel(
            name='HarvestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sell_price_coins', models.PositiveIntegerField(default=15)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_product', to='game.plant')),
            ],
        ),
    ]
