# Generated by Django 6.0 on 2026-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_add_extraction_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_resource',
            field=models.BooleanField(default=False),
        ),
    ]
