# Generated by Django 6.0 on 2026-03-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_is_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='building_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='game.buildingtype'),
        ),
    ]
