# Generated by Django 6.0 on 2026-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_add_building_type_to_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprocess',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipeprocess',
            name='quantity_done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
