# Generated by Django 6.0 on 2025-12-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_inventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='harvest_reward',
        ),
    ]
