# Generated by Django 6.0 on 2025-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_plant_harvest_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(default='hg', max_length=200),
            preserve_default=False,
        ),
    ]
