# Generated by Django 6.0 on 2026-03-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_add_quantity_to_recipe_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='game.skill'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='skill_exp',
            field=models.PositiveIntegerField(default=0, help_text='Опыт навыка за один цикл'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='building_type',
            field=models.CharField(choices=[('field', 'Поле'), ('agroproduction', 'Сельхозпроизводство'), ('extraction', 'Добыча ресурсов'), ('processing', 'Переработка'), ('production', 'Производство')], default='field', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price_coins',
            field=models.PositiveIntegerField(default=0, help_text='Цена продажи (игрок продаёт магазину)'),
        ),
    ]
