# Generated by Django 6.0 on 2025-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_plant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
