# Generated by Django 6.0 on 2025-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_plant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
