# Generated by Django 6.0 on 2025-12-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_plant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Внутренний код, например farming', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('max_level', models.PositiveIntegerField(default=10, verbose_name='Максимальный уровень')),
                ('base_exp', models.PositiveIntegerField(default=50, help_text='Сколько опыта нужно для перехода с 1 на 2 уровень', verbose_name='Опыт до 1 уровня')),
                ('exp_growth', models.FloatField(default=1.3, help_text='Во сколько раз увеличивается требуемый опыт на каждый следующий уровень', verbose_name='Коэффициент роста опыта')),
                ('effect_name', models.CharField(help_text='Например: Ускорение роста растений', max_length=100, verbose_name='Название эффекта')),
                ('effect_description', models.TextField(blank=True, help_text='Человеческое описание того, что даёт навык', verbose_name='Описание эффекта')),
                ('effect_value_per_level', models.FloatField(default=0.0, help_text='Например: 1.0 = +1% скорости за уровень', verbose_name='Значение эффекта за уровень')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
