# Generated by Django 6.0 on 2025-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_skill_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='grow_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Фактическое время роста с учётом навыков', null=True),
        ),
    ]
