# Generated by Django 6.0 on 2025-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_cell_grow_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
