# Generated by Django 6.0 on 2025-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_userskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
