# Generated by Django 6.0 on 2026-01-07 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_shopproduct_shopresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_owner_seed_type',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_owner_product_type',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='harvest_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.harvestproduct'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.shopresource'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shop_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.shopproduct'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('seed', 'Семя'), ('resource', 'Ресурс магазина'), ('shop_product', 'Продукт магазина'), ('harvest_product', 'Урожай')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.seed'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'seed')), fields=('owner', 'seed'), name='uniq_owner_seed'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'resource')), fields=('owner', 'resource'), name='uniq_owner_resource'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'shop_product')), fields=('owner', 'shop_product'), name='uniq_owner_shop_product'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'harvest_product')), fields=('owner', 'harvest_product'), name='uniq_owner_harvest_product'),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
    ]
