# Generated by Django 6.0 on 2026-01-07 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_remove_inventoryitem_uniq_owner_seed_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestproduct',
            options={'verbose_name': 'Урожай', 'verbose_name_plural': 'Урожай'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'verbose_name': 'Профиль игрока'},
        ),
        migrations.AlterModelOptions(
            name='seed',
            options={'verbose_name': 'Семя', 'verbose_name_plural': 'Семена'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'Продукт магазина', 'verbose_name_plural': 'Продукты магазина'},
        ),
        migrations.AlterModelOptions(
            name='shopresource',
            options={'verbose_name': 'Ресурс магазина', 'verbose_name_plural': 'Ресурсы магазина'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='cell',
            name='grow_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Фактическое время роста с учетом навыков', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('seed', 'Семя'), ('resource', 'Ресурс'), ('shop_product', 'Продукт магазина'), ('harvest_product', 'Урожай')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvest_yield',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='seed_price',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopresource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='base_exp',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='effect_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='effect_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='effect_value_per_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='exp_growth',
            field=models.FloatField(default=1.3),
        ),
        migrations.AlterField(
            model_name='skill',
            name='max_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['owner'], name='game_cell_owner_i_84868a_idx'),
        ),
    ]
