# Generated by Django 6.0 on 2026-01-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_harvestproduct_options_alter_plant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price_coins', models.PositiveIntegerField(default=0)),
                ('is_seed', models.BooleanField(default=False)),
                ('is_harvest', models.BooleanField(default=False)),
                ('grow_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('harvest_yield', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='harvestproduct',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='plant',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_owner_seed',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_owner_resource',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_owner_shop_product',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_owner_harvest_product',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.itemcategory'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='harvest_item',
            field=models.ForeignKey(blank=True, help_text='Если это семя, то сюда ставим связанный урожай', limit_choices_to={'is_harvest': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_item', to='game.shopitem'),
        ),
        migrations.AddField(
            model_name='cell',
            name='shop_item',
            field=models.ForeignKey(blank=True, help_text='Что посажено в этой ячейке', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.shopitem'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.shopitem'),
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='harvest_product',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='shop_product',
        ),
        migrations.DeleteModel(
            name='HarvestProduct',
        ),
        migrations.DeleteModel(
            name='ShopResource',
        ),
        migrations.DeleteModel(
            name='Seed',
        ),
        migrations.DeleteModel(
            name='ShopProduct',
        ),
    ]
